FROM node:20-slim AS build

WORKDIR /app
COPY package.json .
RUN npm install --no-audit --no-fund
COPY . .

ARG VITE_AUTH_SERVICE_URL
ARG VITE_ML_SERVICE_URL
ARG VITE_AUDIT_SERVICE_URL
ENV VITE_AUTH_SERVICE_URL=$VITE_AUTH_SERVICE_URL
ENV VITE_ML_SERVICE_URL=$VITE_ML_SERVICE_URL
ENV VITE_AUDIT_SERVICE_URL=$VITE_AUDIT_SERVICE_URL

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
